bs - create the class for the basic MongoDB collection (admin can see subject area updates)
ucsb-cs156-s23/proj-courses-s23-7pm-4 pull request #42
Opened 2023-06-05 20:05 UTC by BrennaScholte

In this pull request I created the class for the basic MongoDB collection, in Update.java. In this class I defined the three string variables: subject_area, quarter_yyyyq, last_update.

This PR is part of implementing the whole feature titled "Admins can see when a subject area was last updated".

Closes: #35

2023-06-05 21:03 UTC, kkwen123 submitted a review, later dismissed
LGTM

2023-06-05 21:41 UTC, pconrad requested changes
One small change

2023-06-05 21:41 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/documents/Update.java
> +    private String last_update;
This is probably better:

```suggestion
    private ZonedDateTime last_update;
```

See: Job.java under `entities` for examples (and the `import` that's needed).

2023-06-05 22:58 UTC, kkwen123 approved these changes
LGTM

2023-06-06 01:52 UTC, pconrad approved these changes
LGTM

2023-06-06 01:52 UTC, merged