kt - remove quarter from sections in course history table
ucsb-cs156-s23/proj-courses-s23-7pm-4 pull request #44
Opened 2023-06-05 21:19 UTC by kkwen123

In this PR, I changed the Course History Table so that the quarter would not display for sections since the repeated quarter is redundant with an aggregated lecture/section view. 

Before screenshot:
![Screen Shot 2023-06-05 at 2 15 21 PM](https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/assets/78584763/783011df-88b0-482f-a633-60c7c1ef3d7d)

After screenshot: 
![Screen Shot 2023-06-05 at 2 16 15 PM](https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/assets/78584763/16c6ebcf-17b7-4f19-aac2-9b5275f9868e)

storybook link: https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-4/storybook/?path=/docs/components-sections-sectionsovertimetable--empty

2023-06-05 21:45 UTC, pconrad requested changes
Please add "storybook after" link to the PR description:

https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-4/prs/44/storybook/?path=/docs/components-sections-sectionsovertimetable--empty

2023-06-05 21:46 UTC, pconrad approved these changes
LGTM!

2023-06-05 21:46 UTC, pconrad approved these changes
LGTM!

2023-06-06 00:21 UTC, BrennaScholte approved these changes
LGTM

2023-06-06 01:53 UTC, merged